name: Executing Extended Tests, Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: santander-cycles-service

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build ./santander_cycles_service --tag $IMAGE_NAME
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB }}" | docker login  -u philstevenson --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=philstevenson/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.sha	 }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.sha }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "${{ github.ref }}" == "refs/heads/master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME:latest $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  kind-helm:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
          version: "v0.7.0"
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl create namespace cycles
        helm install --wait --namespace cycles cycles ./helm/santander-cycles-service --set image.tag="${{ github.sha }}"
        kubectl get pods --all-namespaces
        kubectl --namespace cycles port-forward svc/cycles-santander-cycles-service 8080:80 &
        sleep 5 && curl --retry 5 --retry-delay 1 -f localhost:8080
