name: Executing Extended Tests, Build & Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: philstevenson/santander-cycles-service

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build ./santander_cycles_service --tag $IMAGE_NAME:local
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB }}" | docker login  -u philstevenson --password-stdin
      - name: Push image
        run: |
          echo VERSION=${{ github.sha }}
          docker tag $IMAGE_NAME:local $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:${{ github.sha }}
          # Use Docker `latest` tag convention if master
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then docker tag $IMAGE_NAME:local $IMAGE_NAME:latest && docker push $IMAGE_NAME:latest; fi

  kind-helm:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.4.0
      with:
          version: "v0.7.0"
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl create namespace cycles
        helm install --wait --namespace cycles cycles ./helm/santander-cycles-service --set image.tag="${{ github.sha }}"
        kubectl get pods --all-namespaces
        kubectl --namespace cycles port-forward svc/cycles-santander-cycles-service 8080:80 &
        sleep 5 && curl --retry 5 --retry-delay 1 -f localhost:8080
